import path from 'node:path';
import {
  ROOT,
  readJson,
  writeText,
  walkW3C,
  pathToCssVar,
  colorToHex,
  CSS_VAR_PREFIX,
} from './lib/token-utils.mjs';

const foundation = readJson(path.join(ROOT, 'tokens/dist/foundation.resolved.json'));
const shadows = readJson(path.join(ROOT, 'tokens/effects/shadows.json'));
const gradients = readJson(path.join(ROOT, 'tokens/effects/gradients.json'));
const textStyles = readJson(path.join(ROOT, 'tokens/typography/text-styles.json'));

const lines = [
  '/* Generated by npm run tokens:build — do not edit */',
  ':root {',
];

for (const { path: parts, token } of walkW3C(foundation)) {
  const type = token.$type;
  let val = token.$value;

  if (type === 'color') val = colorToHex(val);
  else if (type === 'number') val = `${val}px`;
  else if (type === 'string' && parts.join('/') === 'Typography/Font/Icons') {
    val = 'Font Awesome 6 Free';
  }

  if (typeof val === 'string' || typeof val === 'number') {
    lines.push(`  ${pathToCssVar(parts)}: ${val};`);
  }
}

lines.push('');
lines.push('  /* Effects — shadows */');
/** @param {Record<string, unknown>} branch @param {string[]} prefix */
function shadowVars(branch, prefix = []) {
  for (const [key, entry] of Object.entries(branch)) {
    if (key === 'component' && entry && typeof entry === 'object') {
      shadowVars(/** @type {Record<string, unknown>} */ (entry), [...prefix, 'component']);
      continue;
    }
    if (!entry || typeof entry !== 'object' || !('boxShadow' in entry)) continue;
    const e = /** @type {{ boxShadow: string }} */ (entry);
    lines.push(`  ${pathToCssVar(['effect', 'shadow', ...prefix, key])}: ${e.boxShadow};`);
  }
}
shadowVars(shadows);

lines.push('');
lines.push('  /* Effects — gradients */');
for (const [key, entry] of Object.entries(gradients)) {
  const e = /** @type {{ css: string }} */ (entry);
  lines.push(`  ${pathToCssVar(['effect', 'gradient', key])}: ${e.css};`);
}

lines.push('');
lines.push('  /* Composite text styles (font-size / line-height / weight) */');
for (const style of textStyles.styles) {
  const slug = style.name.replace(/\//g, '-').replace(/\s+/g, '-').toLowerCase();
  lines.push(`  --${CSS_VAR_PREFIX}-text-${slug}-font-size: ${style.fontSize}px;`);
  lines.push(`  --${CSS_VAR_PREFIX}-text-${slug}-line-height: ${style.lineHeight}px;`);
  lines.push(`  --${CSS_VAR_PREFIX}-text-${slug}-font-weight: ${style.fontWeight};`);
  if (style.fontStyle === 'italic') {
    lines.push(`  --${CSS_VAR_PREFIX}-text-${slug}-font-style: italic;`);
  }
  if (style.textDecoration !== 'none') {
    lines.push(`  --${CSS_VAR_PREFIX}-text-${slug}-text-decoration: ${style.textDecoration};`);
  }
}

lines.push('}');
lines.push('');

writeText(path.join(ROOT, 'tokens/dist/css/foundation.css'), lines.join('\n'));
console.log('Wrote tokens/dist/css/foundation.css');
